### Get JWT token
POST https://localhost:1443/login
Content-Type: application/json

{
  "username": "user1@veridas.com",
  "password": "1234567890"
}

### Get all users
GET https://localhost:1443/api/users
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

### Get user by ID
GET https://localhost:1443/api/users/1
Authorization: Bearer {{JWT_TOKEN}}

### Get all teachers
GET https://localhost:1443/api/teachers
Authorization: Bearer {{JWT_TOKEN}}

### Get students of a teacher (should fail if teacher's user is inactive)
GET https://localhost:1443/api/teachers/1/students
Authorization: Bearer {{JWT_TOKEN}}

### Update user
PUT https://localhost:1443/api/users/1
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "email": "updateduser@veridas.com",
  "password": "newpassword",
  "type": "admin",
  "active": true
}