### Get JWT token
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "admon@example.com",
  "password": "password"
}

### Get all users
GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

### Get user by ID
GET http://localhost:3000/users/1
Authorization: Bearer {{JWT_TOKEN}}


### Get all teachers
GET http://localhost:3000/api/teachers
Authorization: Bearer {{JWT_TOKEN}}


### Get students of a teacher (should fail if teacher's user is inactive)
GET http://localhost:3000/api/teachers/1/students
Authorization: Bearer {{JWT_TOKEN}}


### Update user
PUT http://localhost:3000/users
Authorization: Bearer {{JWT_TOKEN}}

{
  "email": "updated@example.com",
  "password": "newpassword123",
  "type": "user"
}

### Delete user (should fail if user has associated teacher)
DELETE http://localhost:3000/users/
Authorization: Bearer {{JWT_TOKEN}}

### Get all students
GET http://localhost:3000/students
Authorization: Bearer {{JWT_TOKEN}}

### Get student by ID
GET http://localhost:3000/students/1
Authorization: Bearer {{JWT_TOKEN}}


### Delete student
DELETE http://localhost:3000/students/1
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}